import React, { useState } from 'react';
import { RescueOperation } from '../types';
import { Truck, Users, ShieldAlert, CheckCircle2, Clock, Send, MapPin, Home, ArrowRight } from 'lucide-react';

interface RescueTeamViewProps {
  operations: RescueOperation[];
}

export const RescueTeamView: React.FC<RescueTeamViewProps> = ({ operations }) => {
  const [ops, setOps] = useState<RescueOperation[]>(operations);
  const [selectedOpId, setSelectedOpId] = useState<string>(operations[0]?.id || '');

  const activeOp = ops.find((o) => o.id === selectedOpId) || ops[0];

  const updateOpStatus = (newStatus: RescueOperation['status']) => {
    if (!activeOp) return;
    setOps((prev) =>
      prev.map((o) =>
        o.id === activeOp.id
          ? {
              ...o,
              status: newStatus,
              teams_dispatched:
                newStatus === 'DISPATCHED' ? o.teams_available : o.teams_dispatched,
              last_activity: `Just now — Status changed to ${newStatus}`,
            }
          : o
      )
    );
  };

  const timelineEvents = [
    { time: '01:42 PM', text: 'Critical flood inundation alert generated by XGBoost Risk Engine', active: true },
    { time: '01:44 PM', text: 'Pickup point (Government School Ground) and 8 transport buses assigned', active: true },
    { time: '01:46 PM', text: 'Cell broadcast emergency notification transmitted to 4,230 citizens', active: true },
    { time: '01:49 PM', text: 'NDRF 10th Battalion & SDRF unit deployed with 4 inflatable rescue boats', active: activeOp?.status !== 'STANDBY' },
    { time: '01:58 PM', text: 'First convoy arrived at District Relief Centre shelter; occupancy updated', active: activeOp?.status === 'SHELTER_ARRIVED' },
  ];

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-black text-slate-900 tracking-tight flex items-center gap-2">
            <Truck className="w-6 h-6 text-emerald-700" />
            Field Rescue Team Coordination Console
          </h2>
          <p className="text-xs text-slate-500">
            Real-time emergency unit staging, dispatch authorization, and transit tracking
          </p>
        </div>

        <div className="flex items-center gap-2">
          <span className="px-3 py-1 rounded-full bg-emerald-100 text-emerald-800 text-xs font-bold border border-emerald-300">
            🟢 18 Active Rescue Teams On-Duty
          </span>
        </div>
      </div>

      {/* Main Incident Dashboard */}
      {activeOp && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Left 2 Cols: Incident Details & Dispatch Controls */}
          <div className="lg:col-span-2 space-y-5">
            <div className="bg-white rounded-3xl border border-slate-200 shadow-sm p-6 space-y-6">
              <div className="flex items-start justify-between">
                <div>
                  <span className="px-2.5 py-0.5 rounded-md bg-red-100 text-red-700 text-[10px] font-black tracking-wider uppercase border border-red-200">
                    ACTIVE PRIORITY {activeOp.priority} INCIDENT
                  </span>
                  <h3 className="text-2xl font-black text-slate-900 mt-1">
                    {activeOp.district_name}
                  </h3>
                  <p className="text-xs text-slate-500 flex items-center gap-1 mt-0.5">
                    <ShieldAlert className="w-3.5 h-3.5 text-amber-600" />
                    Hazard: <strong>{activeOp.hazard}</strong> | Last report: {activeOp.last_activity}
                  </p>
                </div>

                <div className="text-right">
                  <div className="text-xs font-bold text-slate-500 uppercase">Operation Status</div>
                  <span className="inline-block mt-1 px-3 py-1 rounded-full text-xs font-black bg-blue-100 text-blue-800 border border-blue-300">
                    {activeOp.status}
                  </span>
                </div>
              </div>

              {/* Metric Counters */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-center">
                <div className="p-3.5 bg-slate-50 rounded-2xl border border-slate-200">
                  <div className="text-[10px] font-bold text-slate-500 uppercase">People at Risk</div>
                  <div className="text-xl font-black text-red-600 mt-0.5">
                    {activeOp.people_at_risk.toLocaleString()}
                  </div>
                </div>

                <div className="p-3.5 bg-slate-50 rounded-2xl border border-slate-200">
                  <div className="text-[10px] font-bold text-slate-500 uppercase">Pickup Points</div>
                  <div className="text-xl font-black text-slate-900 mt-0.5">
                    {activeOp.pickup_points_count} Active
                  </div>
                </div>

                <div className="p-3.5 bg-slate-50 rounded-2xl border border-slate-200">
                  <div className="text-[10px] font-bold text-slate-500 uppercase">Target Shelters</div>
                  <div className="text-xl font-black text-emerald-700 mt-0.5">
                    {activeOp.shelters_count} Prepared
                  </div>
                </div>

                <div className="p-3.5 bg-slate-50 rounded-2xl border border-slate-200">
                  <div className="text-[10px] font-bold text-slate-500 uppercase">Rescue Teams</div>
                  <div className="text-xl font-black text-slate-900 mt-0.5">
                    {activeOp.teams_dispatched} / {activeOp.teams_available}
                  </div>
                </div>
              </div>

              {/* Action Buttons from Section 55 */}
              <div>
                <div className="text-xs font-bold text-slate-700 uppercase tracking-wider mb-2.5">
                  Rescue Command Actions (State Machine):
                </div>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                  <button
                    onClick={() => updateOpStatus('STANDBY')}
                    className={`py-2.5 px-3 rounded-xl text-xs font-bold transition-all border cursor-pointer ${
                      activeOp.status === 'STANDBY'
                        ? 'bg-slate-900 text-white border-slate-900 shadow'
                        : 'bg-white text-slate-700 border-slate-200 hover:bg-slate-50'
                    }`}
                  >
                    1. Staging Standby
                  </button>

                  <button
                    onClick={() => updateOpStatus('DISPATCHED')}
                    className={`py-2.5 px-3 rounded-xl text-xs font-bold transition-all border cursor-pointer ${
                      activeOp.status === 'DISPATCHED'
                        ? 'bg-blue-600 text-white border-blue-600 shadow'
                        : 'bg-white text-slate-700 border-slate-200 hover:bg-slate-50'
                    }`}
                  >
                    2. Mark Dispatched
                  </button>

                  <button
                    onClick={() => updateOpStatus('PICKUP_ACTIVE')}
                    className={`py-2.5 px-3 rounded-xl text-xs font-bold transition-all border cursor-pointer ${
                      activeOp.status === 'PICKUP_ACTIVE'
                        ? 'bg-amber-500 text-slate-950 border-amber-500 shadow'
                        : 'bg-white text-slate-700 border-slate-200 hover:bg-slate-50'
                    }`}
                  >
                    3. Pickup Active
                  </button>

                  <button
                    onClick={() => updateOpStatus('SHELTER_ARRIVED')}
                    className={`py-2.5 px-3 rounded-xl text-xs font-bold transition-all border cursor-pointer ${
                      activeOp.status === 'SHELTER_ARRIVED'
                        ? 'bg-emerald-600 text-white border-emerald-600 shadow'
                        : 'bg-white text-slate-700 border-slate-200 hover:bg-slate-50'
                    }`}
                  >
                    4. Shelter Arrived
                  </button>
                </div>
              </div>

              {/* Assigned Vehicle Details */}
              <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 text-xs text-slate-600 space-y-2">
                <div className="font-extrabold text-slate-900 flex items-center gap-1.5">
                  <Truck className="w-4 h-4 text-emerald-700" /> Assigned Transport & Flotilla
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-[11px]">
                  <div>• 8x Ashok Leyland State Transport 54-seater buses</div>
                  <div>• 4x Gemini Inflatable Motor Boats (NDRF Battalion 10)</div>
                  <div>• 2x Tata 407 4WD Mobile Medical Ambulance Units</div>
                  <div>• 1x Satellite Telecommunications Vehicle (VHF/HF Base)</div>
                </div>
              </div>
            </div>
          </div>

          {/* Right Col: Live Operational Timeline (Section 54) */}
          <div className="space-y-4">
            <div className="bg-white rounded-3xl border border-slate-200 shadow-sm p-5 space-y-4">
              <div className="flex items-center justify-between pb-2 border-b border-slate-100">
                <div className="flex items-center gap-2">
                  <Clock className="w-4 h-4 text-emerald-700" />
                  <h4 className="font-extrabold text-sm text-slate-900">Incident Event Timeline</h4>
                </div>
                <span className="text-[10px] font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-full border border-emerald-200">
                  REAL-TIME LOG
                </span>
              </div>

              <div className="relative pl-6 space-y-5 before:absolute before:left-2 before:top-2 before:bottom-2 before:w-0.5 before:bg-slate-200">
                {timelineEvents.map((ev, i) => (
                  <div key={i} className="relative">
                    <div
                      className={`absolute -left-6 top-1 w-3.5 h-3.5 rounded-full border-2 border-white ${
                        ev.active ? 'bg-emerald-600' : 'bg-slate-300'
                      }`}
                    />
                    <div className="text-[11px] font-bold text-slate-400">{ev.time}</div>
                    <div className={`text-xs mt-0.5 ${ev.active ? 'font-semibold text-slate-800' : 'text-slate-400'}`}>
                      {ev.text}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Other Sector Incidents */}
            <div className="bg-white rounded-3xl border border-slate-200 shadow-sm p-4 space-y-2">
              <div className="text-xs font-black text-slate-900 uppercase tracking-wider mb-2">
                Other Monitored Incidents
              </div>
              {ops.map((o) => (
                <div
                  key={o.id}
                  onClick={() => setSelectedOpId(o.id)}
                  className={`p-3 rounded-2xl border cursor-pointer transition-all ${
                    o.id === activeOp.id
                      ? 'bg-emerald-50/80 border-emerald-500 shadow-sm'
                      : 'bg-slate-50/50 hover:bg-slate-100 border-slate-200'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <div className="font-extrabold text-xs text-slate-900">{o.district_name}</div>
                    <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-slate-200 text-slate-800">
                      {o.status}
                    </span>
                  </div>
                  <div className="text-[11px] text-slate-500 mt-1">
                    {o.people_at_risk.toLocaleString()} at risk • {o.teams_available} teams
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
